"""Constants for the Section 11 Generator pipeline."""

from __future__ import annotations

EM_385_CATEGORIES: list[str] = [
    "Electrical / Energy Control",
    "Fall Protection & Prevention",
    "Excavation & Trenching",
    "Confined Space Entry",
    "Cranes & Rigging",
    "Demolition",
    "Material Handling & Storage",
    "Fire Prevention & Hot Work",
    "Scaffolding & Access Systems",
    "Hazardous Energy / LOTO",
    "Environmental Controls",
    "Mechanical Equipment",
    "Structural Work",
    "Diving Operations",
    "Concrete & Masonry",
    "Electrical Testing & Commissioning",
    "Radiation & Lasers",
    "Unmapped",
]

DEFAULT_CATEGORY_BY_KEYWORD: dict[str, str] = {
    "electrical": "Electrical / Energy Control",
    "energy": "Electrical / Energy Control",
    "fall": "Fall Protection & Prevention",
    "trench": "Excavation & Trenching",
    "confined space": "Confined Space Entry",
    "crane": "Cranes & Rigging",
    "rigging": "Cranes & Rigging",
    "demolition": "Demolition",
    "material": "Material Handling & Storage",
    "handling": "Material Handling & Storage",
    "storage": "Material Handling & Storage",
    "hot work": "Fire Prevention & Hot Work",
    "welding": "Fire Prevention & Hot Work",
    "scaffold": "Scaffolding & Access Systems",
    "loto": "Hazardous Energy / LOTO",
    "lockout": "Hazardous Energy / LOTO",
    "tagout": "Hazardous Energy / LOTO",
    "environment": "Environmental Controls",
    "mechanical": "Mechanical Equipment",
    "structural": "Structural Work",
    "diving": "Diving Operations",
    "concrete": "Concrete & Masonry",
    "masonry": "Concrete & Masonry",
    "testing": "Electrical Testing & Commissioning",
    "commission": "Electrical Testing & Commissioning",
    "laser": "Radiation & Lasers",
    "radiation": "Radiation & Lasers",
}

HAZARD_KEYWORDS: list[str] = [
    "shock",
    "arc",
    "fall",
    "trench",
    "confined",
    "asphyxiation",
    "entanglement",
    "lockout",
    "tagout",
    "hazard",
    "fire",
    "explosion",
    "crush",
    "caught-between",
    "struck-by",
    "struck by",
    "energized",
    "energized work",
    "rigging",
    "load drop",
    "collapse",
    "dust",
    "silica",
    "chemical",
    "toxic",
]

SCOPE_LINE_KEYWORDS: list[str] = [
    "scope",
    "work includes",
    "work consists",
    "activities include",
    "project includes",
]

